title: "AI Document (.NET tool)"
description: "ðŸ§  ðŸ¤– AI-powered documentation generator. Leveraging OpenAI's API, this tool analyzes your code and generates meaningful, human-readable documentation with the help of advanced AI."
baseurl: "dotnet-aidocument"
minimal_mistakes_skin: "plum"
remote_theme: "mmistakes/minimal-mistakes"
repository: "guibranco/dotnet-aidocument"
logo: "docs/images/logo.png"
name: "Guilherme Branco Stracini"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
atom_feed:
  hide: true
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:guilherme@guilhermebranco.com.br"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://guilhermebranco.com.br"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/guibranco"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/guilherme.stracini"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/guibranco"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/gui.stracini"
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
